CREATE TABLE `USER` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `LOGIN` VARCHAR(30) NOT NULL,
  `PASSWORD` VARCHAR(50) NOT NULL,
  `ROLE` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`USER_ID`));

CREATE TABLE `CUSTOMER` (
  `CUSTOMER_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `FIRST_NAME` VARCHAR(50) NOT NULL,
  `LAST_NAME` VARCHAR(50) NOT NULL,
  `DOB` DATE ,
  `EMAIL` VARCHAR(50) NULL,
  `PHONE` VARCHAR(20) NULL,
  `GENDER` TINYINT(1) NOT NULL,
  `INFORMATION` VARCHAR(200) NULL,
  `DISCOUNT` INT NULL,
  PRIMARY KEY (`CUSTOMER_ID`)
);

CREATE TABLE `RESULTS` (
  `RESULT_ID` INT NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` INT NOT NULL,
  `WEIGHT` DECIMAL(5,2) NOT NULL,
  `WAIST` DECIMAL(5,2) NULL,
  `THIGH` DECIMAL(5,2) NULL,
  `CHEST` DECIMAL(5,2) NULL,
  `HEIGHT` DECIMAL(5,2) NOT NULL,
  `MEASUREMENT_DATE` DATE NULL,
  PRIMARY KEY (`RESULT_ID`)
);

CREATE TABLE `RECIPE` (
  `RECIPE_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL,
  `DESCRIPTION` VARCHAR(2000) NOT NULL,
  `LINK` VARCHAR(200) NULL,
  PRIMARY KEY (`RECIPE_ID`));

CREATE TABLE `MEAL` (
  `MEAL_ID` INT NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` INT NOT NULL,
  `RECIPE_ID` INT NOT NULL,
  `TYPE` CHAR(1) NOT NULL,
  `MEAL_DATE` DATE,
  PRIMARY KEY (`MEAL_ID`)
);

CREATE TABLE `EXERCISE` (
  `EXERCISE_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NOT NULL ,
  `DESCRIPTION` VARCHAR(2000) NOT NULL,
  `LINK` VARCHAR(200) NULL,
  PRIMARY KEY (`EXERCISE_ID`));

CREATE TABLE `TRAINING` (
  `TRAINING_ID` INT NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` INT NOT NULL,
  `EXERCISE_ID` INT NOT NULL,
  `NUMBER` INT NULL,
  `WEIGHT` INT NULL,
  `TRAINING_DATE` DATE NULL,
  `STATUS` TINYINT(1) NULL,
  PRIMARY KEY (`TRAINING_ID`)
  );

CREATE TABLE `TRAINER` (
  `TRAINER_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL,
  `FIRST_NAME` VARCHAR(50) NOT NULL,
  `LAST_NAME` VARCHAR(50) NOT NULL,
  `SPECIALIZATION` VARCHAR(100) NULL,
  PRIMARY KEY (`TRAINER_ID`)
);

CREATE TABLE `REVIEW` (
  `REVIEW_ID` INT NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` INT NOT NULL,
  `TRAINER_ID` INT NOT NULL,
  `COMMENT` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`REVIEW_ID`));
  
  CREATE TABLE `ORDER` (
  `ORDER_ID` INT NOT NULL AUTO_INCREMENT,
  `CUSTOMER_ID` INT NOT NULL,
  `TRAINER_ID` INT NOT NULL,
  `NUMBER` INT NOT NULL,
  `PRICE` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`ORDER_ID`));
 