-- user
INSERT INTO `USER` (`LOGIN`,`PASSWORD`,`ROLE`) VALUES ('admin','adminpassword','admin');
INSERT INTO `USER` (`LOGIN`,`PASSWORD`,`ROLE`) VALUES ('ivanov@gmail.com','ivanovpassword','tr');
INSERT INTO `USER` (`LOGIN`,`PASSWORD`,`ROLE`) VALUES ('petrov@gmail.com','petrovpassword','tr');
INSERT INTO `USER` (`LOGIN`,`PASSWORD`,`ROLE`) VALUES ('smirvova@gmail.com','smirnovapassword','tr');
INSERT INTO `USER` (`LOGIN`,`PASSWORD`,`ROLE`) VALUES ('orlova@gmail.com','orlovapassword','tr');
INSERT INTO `USER` (`LOGIN`,`PASSWORD`,`ROLE`) VALUES ('danilov@gmail.com','danilovpassword','cus');
INSERT INTO `USER` (`LOGIN`,`PASSWORD`,`ROLE`) VALUES ('vasilieva@gmail.com','vasilievapassword','cus');
INSERT INTO `USER` (`LOGIN`,`PASSWORD`,`ROLE`) VALUES ('anisimov@gmail.com','anisimovpassword','cus');
INSERT INTO `USER` (`LOGIN`,`PASSWORD`,`ROLE`) VALUES ('belousova@gmail.com','belousovapassword','cus');
INSERT INTO `USER` (`LOGIN`,`PASSWORD`,`ROLE`) VALUES ('fokin@gmail.com','fokinpassword','cus');

-- trainer
INSERT INTO `TRAINER` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`, `SPECIALIZATION`) VALUES (2, 'Ivan', 'Ivanov', 'pilates');
INSERT INTO `TRAINER` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`, `SPECIALIZATION`) VALUES (3, 'Oleg', 'Petrov', 'aerobics');
INSERT INTO `TRAINER` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`, `SPECIALIZATION`) VALUES (4, 'Anna', 'Smirnova', 'zumba');
INSERT INTO `TRAINER` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`, `SPECIALIZATION`) VALUES (5, 'Irina', 'Orlova', 'crossfit');

-- customer
INSERT INTO `CUSTOMER` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`, `DOB`, `EMAIL`, `PHONE`, `GENDER`, `INFORMATION`, `DISCOUNT`) VALUES (6, 'Pavel', 'Danilov', '1995-01-12', 'danilov@gmail.com', '80295894689', 1, 'allergic to honey', 10);
INSERT INTO `CUSTOMER` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`, `DOB`, `EMAIL`, `PHONE`, `GENDER`, `INFORMATION`, `DISCOUNT`) VALUES (7, 'Marina', 'Vasilieva', '1965-10-14', 'vasilieva@gmail.com', '80298746598', 0, 'diabetic', 20);
INSERT INTO `CUSTOMER` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`, `DOB`, `EMAIL`, `PHONE`, `GENDER`) VALUES (8, 'Viktor', 'Anisimov', '1976-03-03', 'anisimov@gmail.com', '80294521106', 1);
INSERT INTO `CUSTOMER` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`, `DOB`, `EMAIL`, `PHONE`, `GENDER`, `INFORMATION`) VALUES (9, 'Polina', 'Belousova', '1988-04-26', 'belousova@gmail.com', '80297651499', 0, 'tachycardia');
INSERT INTO `CUSTOMER` (`USER_ID`,`FIRST_NAME`,`LAST_NAME`, `DOB`, `EMAIL`, `PHONE`, `GENDER`, `DISCOUNT`) VALUES (10, 'Artur' , 'Fokin', '1991-10-19', 'fokin@gmail.com', '80298872645', 1, 10);

-- recipe
INSERT INTO `RECIPE` (`NAME`, `DESCRIPTION`) VALUES ('egg toast', '26 carbs, 9 fat, 12 protein, 230 calories');
INSERT INTO `RECIPE` (`NAME`, `DESCRIPTION`) VALUES ('buckwheat porridge', '20 сarbs, 3 fat, 4 protein, 97 calories');
INSERT INTO `RECIPE` (`NAME`, `DESCRIPTION`) VALUES ('pumpkin soup', '8 сarbs, 3 fat, 2 protein, 60 calories');
INSERT INTO `RECIPE` (`NAME`, `DESCRIPTION`) VALUES ('vegetable salad', '4 сarbs, 1 fat, 2 protein, 35 calories');
INSERT INTO `RECIPE` (`NAME`, `DESCRIPTION`) VALUES ('stew', '5 сarbs, 15 fat, 18 protein, 224 calories');
INSERT INTO `RECIPE` (`NAME`, `DESCRIPTION`) VALUES ('cottage cheese', '4 сarbs, 2 fat, 18 protein, 103 calories');
INSERT INTO `RECIPE` (`NAME`, `DESCRIPTION`) VALUES ('mushroom soup', '3 сarbs, 3 fat, 1 protein, 39 calories');
INSERT INTO `RECIPE` (`NAME`, `DESCRIPTION`) VALUES ('vegetable stew', '5 сarbs, 1 fat, 1 protein, 25 calories');
INSERT INTO `RECIPE` (`NAME`, `DESCRIPTION`) VALUES ('pilaf', '10 сarbs, 8 fat, 9 protein, 221 calories');
INSERT INTO `RECIPE` (`NAME`, `DESCRIPTION`) VALUES ('casserole', '11 сarbs, 10 fat, 14 protein, 197 calories');

-- exercise
INSERT INTO `EXERCISE` (`NAME`, `DESCRIPTION`) VALUES ('pushup', 'for chest and arms');
INSERT INTO `EXERCISE` (`NAME`, `DESCRIPTION`) VALUES ('plank', 'for abs and arms');
INSERT INTO `EXERCISE` (`NAME`, `DESCRIPTION`) VALUES ('glute bridge', 'for legs');
INSERT INTO `EXERCISE` (`NAME`, `DESCRIPTION`) VALUES ('spider lunge', 'for legs and abs');
INSERT INTO `EXERCISE` (`NAME`, `DESCRIPTION`) VALUES ('plank tap', 'for abs');
INSERT INTO `EXERCISE` (`NAME`, `DESCRIPTION`) VALUES ('squat', 'for legs');
INSERT INTO `EXERCISE` (`NAME`, `DESCRIPTION`) VALUES ('side lunge', 'for legs');
INSERT INTO `EXERCISE` (`NAME`, `DESCRIPTION`) VALUES ('jumping lunge', 'for legs');
INSERT INTO `EXERCISE` (`NAME`, `DESCRIPTION`) VALUES ('reverse lunge', 'for legs');
INSERT INTO `EXERCISE` (`NAME`, `DESCRIPTION`) VALUES ('walkout', 'for arms and abs');

-- order
INSERT INTO `ORDER` (`CUSTOMER_ID`, `TRAINER_ID`, `NUMBER`, `PRICE`) VALUES (1, 1, 10, 90);
INSERT INTO `ORDER` (`CUSTOMER_ID`, `TRAINER_ID`, `NUMBER`, `PRICE`) VALUES (2, 4, 20, 160);
INSERT INTO `ORDER` (`CUSTOMER_ID`, `TRAINER_ID`, `NUMBER`, `PRICE`) VALUES (3, 2, 8, 80);
INSERT INTO `ORDER` (`CUSTOMER_ID`, `TRAINER_ID`, `NUMBER`, `PRICE`) VALUES (4, 3, 15, 150);
INSERT INTO `ORDER` (`CUSTOMER_ID`, `TRAINER_ID`, `NUMBER`, `PRICE`) VALUES (5, 1, 25, 225);

-- review
INSERT INTO `REVIEW` (`CUSTOMER_ID`, `TRAINER_ID`, `COMMENT`) VALUES (1, 1, 'great workouts');
INSERT INTO `REVIEW` (`CUSTOMER_ID`, `TRAINER_ID`, `COMMENT`) VALUES (3, 2, 'so-so');
INSERT INTO `REVIEW` (`CUSTOMER_ID`, `TRAINER_ID`, `COMMENT`) VALUES (4, 3, 'wonderful, I recommend to all');
INSERT INTO `REVIEW` (`CUSTOMER_ID`, `TRAINER_ID`, `COMMENT`) VALUES (5, 1, 'very good');

-- results
INSERT INTO `RESULTS` (`CUSTOMER_ID`, `WEIGHT`, `WAIST`, `THIGH`, `CHEST`, `HEIGHT`, `MEASUREMENT_DATE`) VALUES (1, 80, 100, 82, 98, 180, '2017-09-02');
INSERT INTO `RESULTS` (`CUSTOMER_ID`, `WEIGHT`, `WAIST`, `THIGH`, `CHEST`, `HEIGHT`, `MEASUREMENT_DATE`) VALUES (1, 82, 97, 78, 100, 180, '2017-10-05');
INSERT INTO `RESULTS` (`CUSTOMER_ID`, `WEIGHT`, `WAIST`, `THIGH`, `CHEST`, `HEIGHT`, `MEASUREMENT_DATE`) VALUES (1, 85, 97, 77, 102, 180, '2017-11-11');
INSERT INTO `RESULTS` (`CUSTOMER_ID`, `WEIGHT`, `WAIST`, `THIGH`, `CHEST`, `HEIGHT`, `MEASUREMENT_DATE`) VALUES (2, 62, 96, 63, 92, 168, '2017-09-04');
INSERT INTO `RESULTS` (`CUSTOMER_ID`, `WEIGHT`, `WAIST`, `THIGH`, `CHEST`, `HEIGHT`, `MEASUREMENT_DATE`) VALUES (2, 58, 93, 60, 92, 168, '2017-10-04');
INSERT INTO `RESULTS` (`CUSTOMER_ID`, `WEIGHT`, `WAIST`, `THIGH`, `CHEST`, `HEIGHT`, `MEASUREMENT_DATE`) VALUES (3, 96, 103, 82, 107, 185, '2017-10-15');
INSERT INTO `RESULTS` (`CUSTOMER_ID`, `WEIGHT`, `WAIST`, `THIGH`, `CHEST`, `HEIGHT`, `MEASUREMENT_DATE`) VALUES (3, 90, 100, 80, 106, 186, '2017-11-29');
INSERT INTO `RESULTS` (`CUSTOMER_ID`, `WEIGHT`, `WAIST`, `THIGH`, `CHEST`, `HEIGHT`, `MEASUREMENT_DATE`) VALUES (4, 56, 92, 62, 89, 162, '2017-09-25');
INSERT INTO `RESULTS` (`CUSTOMER_ID`, `WEIGHT`, `WAIST`, `THIGH`, `CHEST`, `HEIGHT`, `MEASUREMENT_DATE`) VALUES (4, 53, 90, 60, 87, 162, '2017-11-03');
INSERT INTO `RESULTS` (`CUSTOMER_ID`, `WEIGHT`, `WAIST`, `THIGH`, `CHEST`, `HEIGHT`, `MEASUREMENT_DATE`) VALUES (5, 68, 96, 69, 97, 172, '2017-10-19');
INSERT INTO `RESULTS` (`CUSTOMER_ID`, `WEIGHT`, `WAIST`, `THIGH`, `CHEST`, `HEIGHT`, `MEASUREMENT_DATE`) VALUES (5, 72, 98, 72, 100, 173, '2017-11-30');

-- meal
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (1, 1, 'b', '2017-09-10'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (1, 5, 'l', '2017-09-10'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (1, 6, 'd', '2017-09-10'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (1, 2, 'b', '2017-11-12'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (1, 9, 'l', '2017-11-12'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (1, 3, 'd', '2017-11-12'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (2, 5, 'b', '2017-09-06'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (2, 2, 'l', '2017-09-06'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (2, 9, 'd', '2017-09-06'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (2, 10, 'b', '2017-10-05'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (2, 5, 'l', '2017-10-05'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (2, 4, 'd', '2017-10-05'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (3, 1, 'b', '2017-10-17'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (3, 5, 'l', '2017-10-17'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (3, 4, 'd', '2017-10-17'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (4, 10, 'b', '2017-11-01'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (4, 8, 'l', '2017-11-01'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (4, 4, 'd', '2017-11-01');
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (5, 8, 'b', '2017-10-22'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (5, 5, 'l', '2017-10-22'); 
INSERT INTO `MEAL` (`CUSTOMER_ID`, `RECIPE_ID`, `TYPE`, `MEAL_DATE`) VALUES (5, 6, 'd', '2017-10-22');

-- training
INSERT INTO `TRAINING` (`CUSTOMER_ID`, `EXERCISE_ID`, `NUMBER`, `TRAINING_DATE`, `STATUS`) VALUES (1, 6, 300, '2017-09-03', true);
INSERT INTO `TRAINING` (`CUSTOMER_ID`, `EXERCISE_ID`, `NUMBER`, `TRAINING_DATE`, `STATUS`) VALUES (1, 2, 100, '2017-09-12', true);
INSERT INTO `TRAINING` (`CUSTOMER_ID`, `EXERCISE_ID`, `NUMBER`, `TRAINING_DATE`, `STATUS`) VALUES (1, 8, 200, '2017-09-20', false);
INSERT INTO `TRAINING` (`CUSTOMER_ID`, `EXERCISE_ID`, `NUMBER`, `TRAINING_DATE`, `STATUS`) VALUES (1, 10, 30, '2017-09-25', true);
INSERT INTO `TRAINING` (`CUSTOMER_ID`, `EXERCISE_ID`, `NUMBER`, `WEIGHT`, `TRAINING_DATE`, `STATUS`) VALUES (2, 1, 20, 2, '2017-10-18', true);
INSERT INTO `TRAINING` (`CUSTOMER_ID`, `EXERCISE_ID`, `NUMBER`, `TRAINING_DATE`, `STATUS`) VALUES (2, 3, 200, '2017-10-27', true);
INSERT INTO `TRAINING` (`CUSTOMER_ID`, `EXERCISE_ID`, `NUMBER`, `TRAINING_DATE`, `STATUS`) VALUES (3, 5, 50, '2017-10-30', false);
INSERT INTO `TRAINING` (`CUSTOMER_ID`, `EXERCISE_ID`, `NUMBER`, `TRAINING_DATE`, `STATUS`) VALUES (3, 4, 300, '2017-11-11', true);
INSERT INTO `TRAINING` (`CUSTOMER_ID`, `EXERCISE_ID`, `NUMBER`, `TRAINING_DATE`, `STATUS`) VALUES (4, 7, 200, '2017-09-28', true);
INSERT INTO `TRAINING` (`CUSTOMER_ID`, `EXERCISE_ID`, `NUMBER`, `TRAINING_DATE`, `STATUS`) VALUES (4, 9, 200, '2017-10-17', true);
INSERT INTO `TRAINING` (`CUSTOMER_ID`, `EXERCISE_ID`, `NUMBER`, `TRAINING_DATE`, `STATUS`) VALUES (5, 1, 50, '2017-10-20', true);
